[project]
name = "python-samples"
version = "0.1.0"
description = ""
authors = [
    {name = "kenux196",email = "kenux.yun@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11,<4.0"
dependencies = [
    "reportlab (>=4.3.1,<5.0.0)",
    "pydub (>=0.25.1,<0.26.0)",
]